### ISSUE TITLE
Not logging in? 

### ISSUE THREAD

**Issue by MorningStarGG** [LethalMaus/StreamingYorkie#43]
Since about a month I cannot login it just sits on a white page after authorization that said it'll redirect me automatically and never does. I even tried the "click here" too. Android 12 on Samsung Galaxy S20 Plus.

**Comment by LethalMaus** [comment]
The app was removed from the store March 2021 and support for the app has been dropped. Sorry for the inconvenience

**Comment by MorningStarGG** [comment]
Do you know of any alternatives on either desktop or mobile?

**Comment by LethalMaus** [comment]
Sorry I dont

**Comment by MorningStarGG** [comment]
May I ask why this app was dropped? If not that's fine. I'm sure I'm not the only one who loved using this app.

**Comment by LethalMaus** [comment]
The app used Twitchs API. Twitch dropped support of critical features on
their side which affected the app. This was the main cause for support and
further development being dropped and the app was removed from the store

**Comment by MorningStarGG** [comment]
Damn, I wish a workaround could be found. The auto export was useful. I knew they switched APIs but didn't know the new one (Helix) changed enough to break this. While it was logged in it was still exporting but then I had to reset app and now I cannot even log in just for that feature. :(

**Comment by LethalMaus** [comment]
Sorry for the inconvenience and hope you find an alternative
