### ISSUE TITLE
green heart at the bottom

### ISSUE THREAD

**Issue by Rosentreter** [LethalMaus/StreamingYorkie#8]
There is a green heart at the bottom. If tap on the heart it disappear. Nothing else happens.
Is this maybe a bug?

![a20b39fb-417c-491e-b525-63661d68d98e](https://user-images.githubusercontent.com/48011516/55009029-33b1bc00-4fe2-11e9-9809-db1e787742f5.jpg)

**Comment by LethalMaus** [comment]
Yes this would be considered a bug. The heart should not be there when their is less than 2 users to display.
This will be fixed & closed within the next release.
Thank you

**Comment by LethalMaus** [comment]
@quaitzel the fix should be in. Please confirm so that I can close the issue. Thank you

**Comment by LethalMaus** [comment]
Confirmed closed
